In [2]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer, pipeline
import pandas as pd

In [27]:
df = pd.read_csv('articles_goog.csv')

In [28]:
df

      year_month                                              title
0         201501              WikiLeaks Assails Google and the U.S.
1         201501     Google and Fidelity Put $1 Billion Into SpaceX
2         201501  Video Feature: Conjuring the Most From Google ...
3         201501  What Happens if Apple Drops Google From Its Br...
4         201501  A Retreat for Google Glass and a Case Study in...
...          ...                                                ...
1555      202112                   R.T.O. Plans Get Upended. Again.
1556      202112  Where the Despairing Log On, and Learn Ways to...
1557      202112  ‘Fatal Distraction’ Review: Parents Go Through...
1558      202112                               At Home on the Range
1559      202112   How to Use Your Phone’s Privacy-Protection Tools

[1560 rows x 2 columns]

In [29]:
# Carregar o FinBERT
finbert = AutoModelForSequenceClassification.from_pretrained("yiyanghkust/finbert-tone", num_labels=3)
tokenizer = AutoTokenizer.from_pretrained("yiyanghkust/finbert-tone")

# Criar o pipeline
sentiment_pipeline = pipeline("sentiment-analysis", model=finbert, tokenizer=tokenizer)

# Notícias
data = df['title'].tolist()

# Analisar sentimentos
resultados = sentiment_pipeline(data)

# Adicionar as novas colunas ao DataFrame
df['sentimento'] = [resultado['label'] for resultado in resultados]
df['score'] = [resultado['score'] for resultado in resultados]

# Exibir o DataFrame atualizado
print(df)

/home/adriel/anaconda3/lib/python3.11/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

      year_month                                              title  \
0         201501              WikiLeaks Assails Google and the U.S.
1         201501     Google and Fidelity Put $1 Billion Into SpaceX
2         201501  Video Feature: Conjuring the Most From Google ...
3         201501  What Happens if Apple Drops Google From Its Br...
4         201501  A Retreat for Google Glass and a Case Study in...
...          ...                                                ...
1555      202112                   R.T.O. Plans Get Upended. Again.
1556      202112  Where the Despairing Log On, and Learn Ways to...
1557      202112  ‘Fatal Distraction’ Review: Parents Go Through...
1558      202112                               At Home on the Range
1559      202112   How to Use Your Phone’s Privacy-Protection Tools

     sentimento     score
0       Neutral  0.999997
1       Neutral  0.999987
2       Neutral  0.999620
3       Neutral  0.847922
4       Neutral  0.999970
...         ...       ...
1555    Neutral  0.979380
1556    Neutral  0.999692
1557    Neutral  0.581939
1558    Neutral  0.999995
1559    Neutral  0.823807

[1560 rows x 4 columns]

In [49]:
df

,year_month,title,sentimento,score
0,2015-01-01,WikiLeaks Assails Google and the U.S.,Neutral,0.999997
1,2015-01-01,Google and Fidelity Put $1 Billion Into SpaceX,Neutral,0.999987
2,2015-01-01,Video Feature: Conjuring the Most From Google ...,Neutral,0.999620
3,2015-01-01,What Happens if Apple Drops Google From Its Br...,Neutral,0.847922
4,2015-01-01,A Retreat for Google Glass and a Case Study in...,Neutral,0.999970
...,...,...,...,...
1555,2021-12-01,R.T.O. Plans Get Upended. Again.,Neutral,0.979380
1556,2021-12-01,"Where the Despairing Log On, and Learn Ways to...",Neutral,0.999692
1557,2021-12-01,‘Fatal Distraction’ Review: Parents Go Through...,Neutral,0.581939
1558,2021-12-01,At Home on the Range,Neutral,0.999995
1559,2021-12-01,How to Use Your Phone’s Privacy-Protection Tools,Neutral,0.823807

In [41]:
df

,year_month,title,sentimento,score
0,2015-01-01,WikiLeaks Assails Google and the U.S.,Neutral,0.999997
1,2015-01-01,Google and Fidelity Put $1 Billion Into SpaceX,Neutral,0.999987
2,2015-01-01,Video Feature: Conjuring the Most From Google ...,Neutral,0.999620
3,2015-01-01,What Happens if Apple Drops Google From Its Br...,Neutral,0.847922
4,2015-01-01,A Retreat for Google Glass and a Case Study in...,Neutral,0.999970
...,...,...,...,...
1555,2021-12-01,R.T.O. Plans Get Upended. Again.,Neutral,0.979380
1556,2021-12-01,"Where the Despairing Log On, and Learn Ways to...",Neutral,0.999692
1557,2021-12-01,‘Fatal Distraction’ Review: Parents Go Through...,Neutral,0.581939
1558,2021-12-01,At Home on the Range,Neutral,0.999995
1559,2021-12-01,How to Use Your Phone’s Privacy-Protection Tools,Neutral,0.823807

In [42]:
import pandas as pd

# Supondo que df já está definido e possui as colunas 'year_month', 'title', 'sentimento' e 'score'
# Exemplo de DataFrame
# df = pd.DataFrame({
#     'year_month': ['2023-02-01', '2023-02-02', '2023-03-01', '2023-03-02'],
#     'title': ['Notícia 1', 'Notícia 2', 'Notícia 3', 'Notícia 4'],
#     'sentimento': ['positivo', 'negativo', 'positivo', 'positivo'],
#     'score': [0.8, 0.6, 0.9, 0.7]
# })

# Converter a coluna 'year_month' para o formato datetime
df['year_month'] = pd.to_datetime(df['year_month'])

# Agrupar por mês e calcular a média dos scores
df_monthly_avg = df.groupby(df['year_month'].dt.to_period('M')).agg({
    'score': 'mean',
    'sentimento': lambda x: x.mode()[0]  # Sentimento mais frequente
}).reset_index()

# Renomear a coluna 'year_month' para 'month' para maior clareza
df_monthly_avg.rename(columns={'year_month': 'month'}, inplace=True)

# Exibir o DataFrame resultante
print(df_monthly_avg)

      month     score sentimento
0   2015-01  0.934675    Neutral
1   2015-02  0.965849    Neutral
2   2015-03  0.999901    Neutral
3   2015-04  0.985542    Neutral
4   2015-05  0.998832    Neutral
..      ...       ...        ...
79  2021-08  0.960677    Neutral
80  2021-09  0.951174   Negative
81  2021-10  0.946205    Neutral
82  2021-11  0.972133   Negative
83  2021-12  0.934872    Neutral

[84 rows x 3 columns]

In [43]:
df_monthly_avg

      month     score sentimento
0   2015-01  0.934675    Neutral
1   2015-02  0.965849    Neutral
2   2015-03  0.999901    Neutral
3   2015-04  0.985542    Neutral
4   2015-05  0.998832    Neutral
..      ...       ...        ...
79  2021-08  0.960677    Neutral
80  2021-09  0.951174   Negative
81  2021-10  0.946205    Neutral
82  2021-11  0.972133   Negative
83  2021-12  0.934872    Neutral

[84 rows x 3 columns]

In [44]:
df_monthly_avg.rename(columns={'month': 'year_month', 'score':'avg_score'}, inplace=True)

In [48]:
df_monthly_avg[df_monthly_avg['sentimento'] == 'Negative']

   year_month  avg_score sentimento
18    2016-07   0.904891   Negative
31    2017-08   0.956804   Negative
32    2017-09   0.902205   Negative
80    2021-09   0.951174   Negative
82    2021-11   0.972133   Negative

In [46]:
df_monthly_avg.to_csv('avg_monthly_sentiment_scores.csv', index=False)